# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[1.14,)" # Require at least 1.14.x
# License is REQUIRED after 1.16
license='GPL-3.0-or-later'

[[mods]]
modId="configurablezombieai"
version="${file.jarVersion}"
displayName="Configurable Zombie AI"
credits="Special thanks to VarietyCube for pushing me to write everything by hand and avoid vibecoding."
authors="Oggvik"
description='''
A simple mod written in Kotlin that gives server admins several options to customize the vanilla zombie AI as well as some new AI features.
This mod is especially well suited for modpacks aiming to increase the difficulty of the vanilla game or servers.
'''
[[dependencies.configurablezombieai]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configurablezombieai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
